/**
 * Worker entry: canonical-host and trailing-slash redirects, the environment's crawl policy,
 * then the OpenNext-generated handler behind a catalog-epoch-keyed edge cache.
 *
 * Admin paths pass the Cloudflare Access and session-cookie gate first (`lib/auth/admin-gate.ts`).
 *
 * `scheduled()` serves the Cron Triggers in `wrangler.jsonc` (`triggers.crons`): the daily draft
 * reminders and expiry (#63), and later the weekly badge program (#66), in
 * `lib/worker/scheduled.ts`.
 *
 * Wrangler's `main` points here (OpenNext "custom worker" pattern); `.open-next/worker.js`
 * and `.next/routes-manifest.json` are generated by `opennextjs-cloudflare build`. This file
 * is excluded from `tsc` because it imports that build output, so it only wires that output
 * in: the pipeline lives in `lib/worker/handle-request.ts`, `lib/routing/`,
 * `lib/environment/`, and `lib/edge-cache/html-cache.ts`, which are type-checked and
 * unit-tested. See docs/ARCHITECTURE.md#environments-and-hosts,
 * docs/ARCHITECTURE.md#url-canonicalization, and docs/ARCHITECTURE.md#caching.
 */
import {
  catalogEpochToken,
  isUnpublishedListingSlug,
  readCatalogEpoch,
  shareCatalogEpochToken
} from '@serpdirectory/data-ops/catalog-epoch'
import { createDatabase } from '@serpdirectory/data-ops/client'
// Generated by `next build` (inside `opennextjs-cloudflare build`); OpenNext reads the same file.
import routesManifest from './.next/routes-manifest.json'
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import {
  type EdgeCacheContext,
  EpochMemo,
  loadSharedEpoch,
  withEdgeCache
} from './lib/edge-cache/html-cache'
import { goneListingRenderer } from './lib/routing/gone-listing'
import { configRedirectPatterns } from './lib/routing/trailing-slash'
import { handleWorkerRequest } from './lib/worker/handle-request'
import { handleScheduled, type ScheduledEnv } from './lib/worker/scheduled'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

const EDGE_CACHE_NAME = 'edge-html'
/**
 * next.config.ts redirects, which send moved URLs to their canonical page in one hop. A
 * malformed manifest throws here, at startup, so the deploy and every request fail loudly
 * instead of the trailing-slash rule silently switching off.
 */
const configRedirects = loadConfigRedirects()
const runtimeEnvironments = new Set(['local', 'staging', 'production'])

interface WorkerEnv {
  CANONICAL_HOST_REDIRECT?: string
  CF_ACCESS_AUD?: string
  CF_ACCESS_REQUIRED?: string
  CF_ACCESS_TEAM_DOMAIN?: string
  CF_VERSION_METADATA?: { id?: string }
  D1_RUNTIME_ENV?: string
  DB?: D1Database
  SITE_ENVIRONMENT?: string
}

let epochMemo: EpochMemo | undefined

function loadConfigRedirects(): RegExp[] {
  try {
    return configRedirectPatterns(routesManifest)
  } catch (error) {
    console.error(
      JSON.stringify({
        event: 'routes_manifest_invalid',
        message: error instanceof Error ? error.message : String(error)
      })
    )
    throw error
  }
}

function log(event: object): void {
  console.info(JSON.stringify(event))
}

function catalogEpoch(
  env: WorkerEnv,
  cache: Cache
): (context: EdgeCacheContext) => Promise<string | null> {
  // Without a valid binding the cache stays out of the way; the Next.js catalog adapter
  // then fails closed exactly as it does without this entry.
  const database = env.DB
  if (!database || !runtimeEnvironments.has(env.D1_RUNTIME_ENV ?? '')) return async () => null
  epochMemo ||= new EpochMemo(async () => {
    const token = await loadSharedEpoch(cache, async () =>
      catalogEpochToken(
        await readCatalogEpoch({
          asOf: new Date().toISOString(),
          client: createDatabase(database),
          observe: log
        })
      )
    )
    // Renders in this isolate reuse it instead of reading the epoch again (#77).
    shareCatalogEpochToken(token)
    return token
  })
  const memo = epochMemo
  return context => memo.current(context)
}

/**
 * Renders through OpenNext; a listing page's 404 for an unpublished slug becomes the 410 gone
 * page, and no incoming request carries the internal gone-render header
 * (`lib/routing/gone-listing.ts`, #64). Without a valid binding the 404 stands.
 */
function renderer(
  env: WorkerEnv,
  context: ExecutionContext
): (request: Request) => Promise<Response> {
  const render = (request: Request): Promise<Response> =>
    openNextWorker.fetch(request, env, context)
  const database = env.DB
  if (!database || !runtimeEnvironments.has(env.D1_RUNTIME_ENV ?? '')) {
    return goneListingRenderer(render)
  }
  return goneListingRenderer(render, slug =>
    isUnpublishedListingSlug({ client: createDatabase(database), observe: log, slug })
  )
}

export default {
  scheduled(
    controller: ScheduledController,
    env: WorkerEnv & ScheduledEnv,
    context: ExecutionContext
  ): Promise<void> {
    return handleScheduled(controller, env, context)
  },

  fetch(request: Request, env: WorkerEnv, context: ExecutionContext): Promise<Response> {
    const render = renderer(env, context)
    return handleWorkerRequest(request, env, {
      configRedirects,
      // Redirects and the non-production robots.txt are answered before this, so they are
      // never rendered or stored. A cacheable request reaches OpenNext with allowlisted
      // headers only (`renderRequestFor` in lib/edge-cache/html-cache.ts).
      serve: async served => {
        const cache = await caches.open(EDGE_CACHE_NAME)
        return withEdgeCache(
          served,
          context,
          {
            cache,
            deploymentId: env.CF_VERSION_METADATA?.id || 'unversioned',
            epoch: catalogEpoch(env, cache),
            observe: log
          },
          render
        )
      }
    })
  }
}
