/**
 * Worker entry: trailing-slash redirects, then the OpenNext-generated handler behind a
 * catalog-epoch-keyed edge cache.
 *
 * Wrangler's `main` points here (OpenNext "custom worker" pattern); `.open-next/worker.js`
 * and `.next/routes-manifest.json` are generated by `opennextjs-cloudflare build`. This file
 * is excluded from `tsc` because it imports that build output; the redirect and caching
 * logic lives in `lib/routing/trailing-slash.ts` and `lib/edge-cache/html-cache.ts`, which
 * are type-checked and unit-tested. See docs/ARCHITECTURE.md#url-canonicalization and
 * docs/ARCHITECTURE.md#caching.
 */
import { catalogEpochToken, readCatalogEpoch } from '@serpdirectory/data-ops/catalog-epoch'
import { createDatabase } from '@serpdirectory/data-ops/client'
// Generated by `next build` (inside `opennextjs-cloudflare build`); OpenNext reads the same file.
import routesManifest from './.next/routes-manifest.json'
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import {
  type EdgeCacheContext,
  EpochMemo,
  loadSharedEpoch,
  withEdgeCache
} from './lib/edge-cache/html-cache'
import { configRedirectPatterns, trailingSlashRedirect } from './lib/routing/trailing-slash'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

const EDGE_CACHE_NAME = 'edge-html'
/** next.config.ts redirects, which send moved URLs to their canonical page in one hop. */
const configRedirects = configRedirectPatterns(routesManifest)
const runtimeEnvironments = new Set(['local', 'staging', 'production'])

interface WorkerEnv {
  CF_VERSION_METADATA?: { id?: string }
  D1_RUNTIME_ENV?: string
  DB?: D1Database
}

let epochMemo: EpochMemo | undefined

function log(event: object): void {
  console.info(JSON.stringify(event))
}

function catalogEpoch(
  env: WorkerEnv,
  cache: Cache
): (context: EdgeCacheContext) => Promise<string | null> {
  // Without a valid binding the cache stays out of the way; the Next.js catalog adapter
  // then fails closed exactly as it does without this entry.
  const database = env.DB
  if (!database || !runtimeEnvironments.has(env.D1_RUNTIME_ENV ?? '')) return async () => null
  epochMemo ||= new EpochMemo(() =>
    loadSharedEpoch(cache, async () =>
      catalogEpochToken(
        await readCatalogEpoch({
          asOf: new Date().toISOString(),
          client: createDatabase(database),
          observe: log
        })
      )
    )
  )
  const memo = epochMemo
  return context => memo.current(context)
}

export default {
  async fetch(request: Request, env: WorkerEnv, context: ExecutionContext): Promise<Response> {
    // Before the edge cache: a slash variant is never rendered or stored.
    const redirect = trailingSlashRedirect(request, configRedirects)
    if (redirect) return redirect
    const cache = await caches.open(EDGE_CACHE_NAME)
    return withEdgeCache(
      request,
      context,
      {
        cache,
        deploymentId: env.CF_VERSION_METADATA?.id || 'unversioned',
        epoch: catalogEpoch(env, cache),
        observe: log
      },
      () => openNextWorker.fetch(request, env, context)
    )
  }
}
