/**
 * Worker entry: the OpenNext-generated handler behind a catalog-epoch-keyed edge cache.
 *
 * Wrangler's `main` points here (OpenNext "custom worker" pattern); `.open-next/worker.js`
 * is generated by `opennextjs-cloudflare build`. This file is excluded from `tsc` because
 * it imports that build output; the caching logic lives in `lib/edge-cache/html-cache.ts`,
 * which is type-checked and unit-tested. See docs/ARCHITECTURE.md#caching.
 */
import { catalogEpochToken, readCatalogEpoch } from '@serpdirectory/data-ops/catalog-epoch'
import { createDatabase } from '@serpdirectory/data-ops/client'
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import {
  type EdgeCacheContext,
  EpochMemo,
  loadSharedEpoch,
  withEdgeCache
} from './lib/edge-cache/html-cache'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

const EDGE_CACHE_NAME = 'edge-html'
const runtimeEnvironments = new Set(['local', 'staging', 'production'])

interface WorkerEnv {
  CF_VERSION_METADATA?: { id?: string }
  D1_RUNTIME_ENV?: string
  DB?: D1Database
}

let epochMemo: EpochMemo | undefined

function log(event: object): void {
  console.info(JSON.stringify(event))
}

function catalogEpoch(
  env: WorkerEnv,
  cache: Cache
): (context: EdgeCacheContext) => Promise<string | null> {
  // Without a valid binding the cache stays out of the way; the Next.js catalog adapter
  // then fails closed exactly as it does without this entry.
  const database = env.DB
  if (!database || !runtimeEnvironments.has(env.D1_RUNTIME_ENV ?? '')) return async () => null
  epochMemo ||= new EpochMemo(() =>
    loadSharedEpoch(cache, async () =>
      catalogEpochToken(
        await readCatalogEpoch({
          asOf: new Date().toISOString(),
          client: createDatabase(database),
          observe: log
        })
      )
    )
  )
  const memo = epochMemo
  return context => memo.current(context)
}

export default {
  async fetch(request: Request, env: WorkerEnv, context: ExecutionContext): Promise<Response> {
    const cache = await caches.open(EDGE_CACHE_NAME)
    return withEdgeCache(
      request,
      context,
      {
        cache,
        deploymentId: env.CF_VERSION_METADATA?.id || 'unversioned',
        epoch: catalogEpoch(env, cache),
        observe: log
      },
      () => openNextWorker.fetch(request, env, context)
    )
  }
}
