/**
 * Claim holds from a listing domain report (serpcompany/best.serp.co#67, #108 review round 3).
 *
 *   pnpm catalog:claim-holds -- <report.yaml> <manifest-id>
 *       write d1/publications/<manifest-id>.yaml from d1/hygiene/<date>-listing-domains.yaml
 *
 * Every listing in the report's `ownerReview` set (its link ends on another company's domain, or
 * its site is unreachable, #100) gets a `listing-claim-hold-add` operation: an instant claim of
 * it goes to the contact path until the owner clears the hold with `listing-claim-hold-clear`. The
 * manifest is row-level (`concurrency: rows`): each operation checks the listing still has the
 * slug and website the report saw, so it applies on staging and production alike, through the
 * protected Publish D1 Catalog workflow. Re-run `pnpm catalog:domains -- --env production`
 * periodically and generate a new manifest from the new report: holds already placed are left as
 * they are.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, stringify } from 'yaml'
import { parseManifest } from './d1-publisher'

interface ReportEntry {
  class: string
  id: string
  reason?: string
  slug: string
  website: string
}

const REASONS: Record<string, 'off_domain' | 'unreachable'> = {
  'off-domain': 'off_domain',
  unreachable: 'unreachable'
}

/** The manifest for a report's owner-review set, sorted by slug. */
export function claimHoldsManifest(report: string, manifestId: string): string {
  const parsed = parse(report) as { ownerReview?: ReportEntry[] }
  const entries = [...(parsed.ownerReview ?? [])].sort((a, b) => a.slug.localeCompare(b.slug))
  const operations = entries.map(entry => {
    const reason = REASONS[entry.class]
    if (!reason) throw new Error(`Unknown owner-review class ${entry.class} for ${entry.slug}.`)
    return {
      action: 'listing-claim-hold-add',
      id: entry.id,
      slug: entry.slug,
      reason,
      note: (entry.reason ?? entry.class).slice(0, 200),
      expected: { website: entry.website }
    }
  })
  const document = {
    version: 1,
    id: manifestId,
    concurrency: 'rows',
    provenance: { actor: 'devinschumacher', workflow: 'github/publish-d1' },
    operations
  }
  const yaml = `# serpcompany/best.serp.co#67: hold instant claims of #100's owner-review listings (their link
# ends on another company's domain, or their site is unreachable) until the owner decides each.
# Generated by \`pnpm catalog:claim-holds\` from the listing domain report. Row-level: each
# operation checks the listing still has this slug and website.
${stringify(document, { lineWidth: 0 })}`
  parseManifest(yaml)
  return yaml
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const [reportPath, manifestId] = process.argv.slice(2).filter(value => value !== '--')
  if (!reportPath || !manifestId) {
    console.error('Usage: pnpm catalog:claim-holds -- <report.yaml> <manifest-id>')
    process.exit(1)
  }
  const output = resolve('d1/publications', `${manifestId}.yaml`)
  writeFileSync(output, claimHoldsManifest(readFileSync(resolve(reportPath), 'utf8'), manifestId))
  console.log(`Wrote ${output}`)
}
