/**
 * Exact application table and column inventory of the D1 schema in
 * `apps/web/src/db/schema.ts` (applied by the `apps/web/drizzle` migrations).
 * The fresh-schema verification and the seed's tests read every column listed here, so
 * a schema change must update this inventory in the same change.
 */
export const applicationColumnInventory = {
  categories: [
    'id',
    'slug',
    'name',
    'description',
    'sort_order',
    'is_active',
    'created_at',
    'updated_at'
  ],
  listings: [
    'id',
    'slug',
    'name',
    'description',
    'website',
    'content',
    'entity_type',
    'priority',
    'is_unofficial',
    'is_featured',
    'is_active',
    'status',
    'published_at',
    'source_kind',
    'source_identity',
    'source_updated_at',
    'checksum',
    'created_at',
    'updated_at',
    'display_order',
    'source',
    'link_rel'
  ],
  listing_categories: ['listing_id', 'category_id', 'sort_order', 'is_primary'],
  tags: [
    'id',
    'slug',
    'name',
    'description',
    'category_id',
    'sort_order',
    'is_active',
    'created_at',
    'updated_at'
  ],
  listing_tags: ['listing_id', 'tag_id', 'sort_order'],
  best_pages: [
    'id',
    'slug',
    'keyword',
    'title',
    'heading',
    'intro',
    'tag_id',
    'category_id',
    'list_size',
    'keyword_volume',
    'keyword_checked_at',
    'sort_order',
    'is_active',
    'created_at',
    'updated_at'
  ],
  best_page_listings: ['best_page_id', 'listing_id', 'position', 'excluded', 'blurb'],
  taxonomy_redirects: [
    'source_kind',
    'source_slug',
    'target_kind',
    'target_category_id',
    'target_tag_id',
    'target_best_page_id',
    'manifest_id',
    'created_at'
  ],
  listing_media: [
    'id',
    'listing_id',
    'kind',
    'url',
    'sort_order',
    'media_key',
    'sha256',
    'content_type',
    'bytes',
    'width',
    'height'
  ],
  listing_resource_links: ['id', 'listing_id', 'label', 'url', 'sort_order'],
  listing_faqs: ['id', 'listing_id', 'question', 'answer', 'sort_order'],
  publication_state: ['id', 'version', 'manifest_id', 'checksum', 'published_at'],
  migration_runs: [
    'id',
    'schema_version',
    'manifest_identity',
    'input_checksum',
    'target_checksum',
    'affected_records',
    'outcome',
    'error',
    'started_at',
    'completed_at'
  ],
  publication_runs: [
    'id',
    'manifest_id',
    'base_version',
    'published_version',
    'input_checksum',
    'affected_records',
    'affected_routes',
    'outcome',
    'error',
    'started_at',
    'completed_at',
    'actor',
    'workflow',
    'before_checksum',
    'after_checksum'
  ],
  listing_slug_redirects: [
    'id',
    'listing_id',
    'old_slug',
    'new_slug',
    'manifest_id',
    'reason',
    'created_at'
  ],
  listing_submissions: [
    'id',
    'slug',
    'name',
    'description',
    'website',
    'content',
    'category_slug',
    'logo_url',
    'video_url',
    'status',
    'verification_attempts',
    'last_verification_at',
    'last_verification_error',
    'badge_verified_at',
    'reviewed_at',
    'reviewed_by',
    'listing_id',
    'created_at',
    'updated_at',
    'owner_user_id',
    'plan',
    'paid_at',
    'refunded_at',
    'reviewer_note',
    'rejection_reason',
    'rejection_category',
    'draft_saved_at',
    'draft_reminders_sent',
    'draft_last_reminder_at',
    'withdrawal_reason',
    'block_key',
    'block_covers_subdomains',
    'published_checksum',
    'content_version',
    'tag_slugs'
  ],
  listing_submission_resource_links: ['id', 'submission_id', 'label', 'url', 'sort_order'],
  listing_submission_faqs: ['id', 'submission_id', 'question', 'answer', 'sort_order'],
  listing_submission_events: ['id', 'submission_id', 'event_type', 'detail', 'actor', 'created_at'],
  listing_submission_rate_limits: ['fingerprint_hash', 'window_started_at', 'request_count'],
  email_deliveries: [
    'template_id',
    'event_key',
    'provider',
    'status',
    'attempts',
    'provider_message_id',
    'last_error_code',
    'created_at',
    'updated_at'
  ],
  users: ['id', 'name', 'email', 'email_verified', 'image', 'role', 'created_at', 'updated_at'],
  sessions: [
    'id',
    'expires_at',
    'token',
    'created_at',
    'updated_at',
    'ip_address',
    'user_agent',
    'user_id'
  ],
  accounts: [
    'id',
    'account_id',
    'provider_id',
    'user_id',
    'access_token',
    'refresh_token',
    'id_token',
    'access_token_expires_at',
    'refresh_token_expires_at',
    'scope',
    'password',
    'created_at',
    'updated_at'
  ],
  verification: ['id', 'identifier', 'value', 'expires_at', 'created_at', 'updated_at'],
  admin_allowlist: ['email', 'note', 'added_by', 'created_at'],
  auth_rate_limit_hits: ['id', 'bucket', 'hit_at'],
  listing_submission_url_blocks: [
    'id',
    'url_key',
    'submission_id',
    'reason',
    'blocked_by',
    'blocked_at',
    'lifted_at',
    'lifted_by',
    'lift_note',
    'covers_subdomains'
  ],
  listing_owners: [
    'id',
    'listing_id',
    'user_id',
    'role',
    'verified_via',
    'verified_at',
    'revoked_at',
    'revoked_reason',
    'created_at'
  ],
  listing_revisions: [
    'id',
    'listing_id',
    'author_user_id',
    'status',
    'base_checksum',
    'name',
    'description',
    'content',
    'category_slug',
    'logo_url',
    'video_url',
    'reviewer_note',
    'rejection_reason',
    'reviewed_at',
    'reviewed_by',
    'created_at',
    'updated_at',
    'content_version',
    'tag_slugs'
  ],
  listing_revision_resource_links: ['id', 'revision_id', 'label', 'url', 'sort_order'],
  listing_revision_faqs: ['id', 'revision_id', 'question', 'answer', 'sort_order'],
  listing_revision_events: ['id', 'revision_id', 'event_type', 'detail', 'actor', 'created_at'],
  badge_checks: ['id', 'listing_id', 'checked_at', 'outcome', 'reason', 'conclusive', 'kind'],
  listing_claims: [
    'id',
    'listing_id',
    'user_id',
    'method',
    'status',
    'email',
    'email_domain',
    'product_url',
    'listing_website',
    'code_hash',
    'code_sent_at',
    'code_expires_at',
    'codes_sent',
    'attempts',
    'locked_until',
    'email_verified_at',
    'badge_checked_at',
    'badge_attempts',
    'completed_at',
    'created_at',
    'updated_at'
  ],
  listing_claim_holds: ['listing_id', 'reason', 'source', 'created_at', 'cleared_at', 'cleared_by'],
  listing_events: ['id', 'listing_id', 'event_type', 'detail', 'actor', 'created_at'],
  media_ingestions: [
    'id',
    'listing_id',
    'submission_id',
    'revision_id',
    'kind',
    'sort_order',
    'source_url',
    'copy_from_key',
    'status',
    'attempts',
    'next_attempt_at',
    'last_error',
    'media_key',
    'sha256',
    'content_type',
    'bytes',
    'width',
    'height',
    'created_at',
    'updated_at'
  ],
  orders: [
    'id',
    'number',
    'user_id',
    'kind',
    'purpose',
    'target_key',
    'submission_id',
    'listing_id',
    'claim_id',
    'amount_cents',
    'currency',
    'provider',
    'provider_checkout_id',
    'checkout_url',
    'checkout_expires_at',
    'provider_payment_id',
    'provider_refund_id',
    'charged_cents',
    'charged_currency',
    'attention',
    'status',
    'outcome',
    'failure_reason',
    'check_problem',
    'refund_reason',
    'refunded_by',
    'refund_listing_action',
    'refund_badge_check_id',
    'refund_requested_at',
    'refund_attempts',
    'refund_retry_at',
    'refund_note',
    'paid_at',
    'applied_at',
    'refunded_at',
    'failed_at',
    'created_at',
    'updated_at'
  ],
  billing_events: [
    'provider',
    'event_id',
    'event_type',
    'order_id',
    'outcome',
    'received_at',
    'processed_at'
  ]
} as const

export type ApplicationTableName = keyof typeof applicationColumnInventory

export const applicationTableNames = Object.keys(
  applicationColumnInventory
) as ApplicationTableName[]

/** Every row of `table`, ordered by all its columns, so two databases compare row for row. */
export function orderedRowsSql(table: ApplicationTableName): string {
  const columns = applicationColumnInventory[table].map(column => `"${column}"`).join(',')
  return `SELECT ${columns} FROM "${table}" ORDER BY ${columns}`
}

/**
 * Foreign-key order for loading application rows: each table follows the tables it references.
 * It doesn't replay every valid state row by row, because the triggers refuse three kinds of
 * row in this order: a published listing (its primary category loads after it), a retired tag
 * under a retired hub, and a retired tag's memberships. The fixture seed and the scale catalog
 * insert a listing they publish as a draft and publish it once it's filed under its primary
 * category, and insert every tag active and retire the retired ones after their memberships.
 * Neither has a retired tag under a retired hub: loading one means retiring the hub after the
 * tag. A freshly migrated database also already holds the rows a migration seeds
 * (`admin_allowlist`).
 */
export const importOrder: ApplicationTableName[] = [
  'categories',
  'listings',
  'listing_categories',
  'tags',
  'listing_tags',
  'best_pages',
  'best_page_listings',
  'taxonomy_redirects',
  'listing_media',
  'listing_resource_links',
  'listing_faqs',
  'publication_state',
  'migration_runs',
  'publication_runs',
  'listing_slug_redirects',
  'users',
  'sessions',
  'accounts',
  'verification',
  'admin_allowlist',
  'auth_rate_limit_hits',
  'listing_submissions',
  'listing_submission_resource_links',
  'listing_submission_faqs',
  'listing_submission_events',
  'listing_submission_rate_limits',
  'email_deliveries',
  'listing_submission_url_blocks',
  'listing_owners',
  'listing_revisions',
  'listing_revision_resource_links',
  'listing_revision_faqs',
  'listing_revision_events',
  'badge_checks',
  'listing_claims',
  'listing_claim_holds',
  'listing_events',
  'media_ingestions',
  'orders',
  'billing_events'
]

export const toolOwnedTableNames = ['d1_migrations'] as const
